name: Pensamiento Computacional
title: ""
description: ¿Qué es el pensamiento computacional?
twitter:
  username: seppo0010
  card: summary_large_image
image: /computational-thinking/shouldeveryone.png
